export interface Invoice {
  id: string; number: string; accountName?: string; tier: string; cycle: string;
  seats: number; amount: number; currency: string; status: string; source?: string;
  note?: string | null; createdBy?: string | null; issuedAt: string; paidAt?: string | null;
}

const SYMBOL: Record<string, string> = { USD: "$", INR: "₹", EUR: "€", GBP: "£" };
export const money = (n: number, cur = "USD") => `${SYMBOL[cur] ?? cur + " "}${n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const fmtDate = (s: string) => new Date(s).toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
const STATUS_STYLE: Record<string, string> = { PAID: "bg-green-100 text-green-700", DUE: "bg-amber-100 text-amber-700", VOID: "bg-gray-100 text-gray-500" };

/** Opens a clean, isolated print window (Save as PDF) for the invoice. */
function printInvoice(inv: Invoice) {
  const w = window.open("", "_blank", "width=820,height=920");
  if (!w) return;
  const per = inv.seats > 0 ? inv.amount / inv.seats : inv.amount;
  w.document.write(`<!doctype html><html><head><title>${inv.number}</title>
  <style>
    *{box-sizing:border-box;font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif}
    body{margin:0;padding:48px;color:#1f2937}
    .top{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #6366F1;padding-bottom:20px}
    .brand{font-size:26px;font-weight:800}.brand span{color:#6366F1}
    h1{font-size:20px;margin:24px 0 4px}.muted{color:#6b7280;font-size:13px}
    table{width:100%;border-collapse:collapse;margin-top:28px}
    th,td{text-align:left;padding:10px 8px;border-bottom:1px solid #e5e7eb;font-size:14px}
    th{background:#f9fafb;color:#6b7280;text-transform:uppercase;font-size:11px;letter-spacing:.05em}
    .right{text-align:right}.total{font-size:20px;font-weight:800}
    .pill{display:inline-block;padding:3px 10px;border-radius:999px;font-size:12px;font-weight:700;background:#dcfce7;color:#15803d}
    .pill.DUE{background:#fef3c7;color:#b45309}.pill.VOID{background:#f3f4f6;color:#6b7280}
  </style></head><body>
    <div class="top">
      <div><div class="brand">Eagle<span>See</span></div><div class="muted">Workforce visibility platform</div></div>
      <div class="right"><div style="font-size:18px;font-weight:700">INVOICE</div><div class="muted">${inv.number}</div>
        <div style="margin-top:6px"><span class="pill ${inv.status}">${inv.status}</span></div></div>
    </div>
    <h1>Billed to</h1>
    <div>${inv.accountName ?? "—"}</div>
    <div class="muted">Issued ${fmtDate(inv.issuedAt)}${inv.paidAt ? " · Paid " + fmtDate(inv.paidAt) : ""}</div>
    <table>
      <thead><tr><th>Description</th><th class="right">Seats</th><th class="right">Per seat / yr</th><th class="right">Amount</th></tr></thead>
      <tbody><tr>
        <td>${inv.tier} plan — ${inv.cycle === "MONTHLY" ? "Monthly" : "Annual"} subscription</td>
        <td class="right">${inv.seats}</td>
        <td class="right">${money(per, inv.currency)}</td>
        <td class="right">${money(inv.amount, inv.currency)}</td>
      </tr></tbody>
    </table>
    <table><tbody>
      <tr><td class="right" style="border:none">Total due</td><td class="right total" style="border:none;width:180px">${money(inv.amount, inv.currency)}</td></tr>
    </tbody></table>
    ${inv.note ? `<p class="muted" style="margin-top:24px">${inv.note}</p>` : ""}
    <p class="muted" style="margin-top:40px">Thank you. Generated by EagleSee${inv.createdBy && inv.createdBy !== "system" ? " · " + inv.createdBy : ""}.</p>
  </body></html>`);
  w.document.close(); w.focus();
  setTimeout(() => w.print(), 250);
}

export function InvoiceModal({ invoice, onClose }: { invoice: Invoice; onClose: () => void }) {
  const per = invoice.seats > 0 ? invoice.amount / invoice.seats : invoice.amount;
  return (
    <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" onClick={onClose}>
      <div className="w-full max-w-lg rounded-2xl bg-white p-7 shadow-xl" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-start justify-between border-b-2 border-brand pb-4">
          <div>
            <div className="text-2xl font-black text-gray-900">Eagle<span className="text-brand">See</span></div>
            <div className="text-xs text-gray-400">Workforce visibility platform</div>
          </div>
          <div className="text-right">
            <div className="font-bold text-gray-700">INVOICE</div>
            <div className="text-xs text-gray-400">{invoice.number}</div>
            <span className={`mt-1 inline-block rounded-full px-2.5 py-0.5 text-xs font-bold ${STATUS_STYLE[invoice.status] ?? "bg-gray-100 text-gray-500"}`}>{invoice.status}</span>
          </div>
        </div>

        <div className="mt-4">
          <div className="text-xs font-semibold uppercase tracking-wide text-gray-400">Billed to</div>
          <div className="font-semibold text-gray-900">{invoice.accountName ?? "—"}</div>
          <div className="text-xs text-gray-400">Issued {fmtDate(invoice.issuedAt)}{invoice.paidAt && ` · Paid ${fmtDate(invoice.paidAt)}`}</div>
        </div>

        <div className="mt-5 overflow-hidden rounded-xl border border-gray-100">
          <table className="w-full text-sm">
            <thead className="bg-gray-50 text-xs uppercase tracking-wide text-gray-500">
              <tr><th className="px-3 py-2 text-left">Description</th><th className="px-3 py-2 text-right">Seats</th><th className="px-3 py-2 text-right">Amount</th></tr>
            </thead>
            <tbody>
              <tr className="border-t border-gray-100">
                <td className="px-3 py-2.5"><div className="font-medium text-gray-800">{invoice.tier} plan</div><div className="text-xs text-gray-400">{invoice.cycle === "MONTHLY" ? "Monthly" : "Annual"} · {money(per, invoice.currency)}/seat/yr</div></td>
                <td className="px-3 py-2.5 text-right text-gray-600">{invoice.seats}</td>
                <td className="px-3 py-2.5 text-right font-semibold text-gray-800">{money(invoice.amount, invoice.currency)}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="mt-3 flex items-center justify-end gap-3">
          <span className="text-sm text-gray-500">Total</span>
          <span className="text-2xl font-black text-gray-900">{money(invoice.amount, invoice.currency)}</span>
        </div>
        {invoice.note && <p className="mt-3 text-sm text-gray-500">{invoice.note}</p>}

        <div className="mt-6 flex justify-end gap-2">
          <button onClick={onClose} className="rounded-lg bg-gray-100 px-4 py-2 text-sm font-semibold text-gray-700">Close</button>
          <button onClick={() => printInvoice(invoice)} className="rounded-lg bg-brand px-5 py-2 text-sm font-bold text-white hover:bg-brand-dark">Print / Save PDF</button>
        </div>
      </div>
    </div>
  );
}
